### ISSUE TITLE
Better radio fw for wifi?

### ISSUE THREAD

**Issue by alecuba16** [xingrz/android_vendor_meizu_sdm710-common#1]
I got between -60~-63 dbm with original  Flyme 8.20.6.30A, with the radio that you provide I got -67~-70 dbm in the same place, same router, same devices.

I repeated the test many times and I get this 5dbm difference (better in original Meizu FW) between your radio and original Meizu, is it possible?

**Comment by xingrz** [comment]
The radio firmware was extracted from the original Flyme OTA. No difference technically.

**Comment by alecuba16** [comment]
Seems that the difference is on flyme fw itself, the radio included in the 8.20.6.30A is better than the version that you have included, I updated manually the files in your package and the rssi is 4-5 dbm better (lower).

Another point is it possible to manipulate the radio config of wpa_supplicant or wifi cfg of the firmware to disconnect at the -90dbm instead as 75 or 80. (original Meizu FW radio disconnects at 90dbm approx)

[RADIO-m1872-20200720101605.zip](https://we.tl/t-ktKqTYQl7X)

**Comment by xingrz** [comment]
> the radio included in the 8.20.6.30A is better than the version that you have included

Thanks for your information.
